name: ph_mobile
description: pH Station mobile configurer.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: 3.7.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  firebase_core: ^2.5.0
  firebase_auth: ^4.2.6

  get_it: ^7.2.0
  intl: ^0.17.0
  flex_color_scheme: ^6.1.2
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  email_validator: ^2.1.17
  meta: ^1.8.0
  json_annotation: ^4.8.0
  easy_splash_screen: ^1.0.4

dev_dependencies:
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.1
  build_runner: ^2.3.3

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg