// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsm4d26ZavQgtlqEpKYjlGUZvtH30zxOE',
    appId: '1:348513316290:android:7a9c5baba649e38e8aba5b',
    messagingSenderId: '348513316290',
    projectId: 'ufg-pfc-sonda-ph',
    storageBucket: 'ufg-pfc-sonda-ph.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqzueWDi4U11lqyFf8nFs_EFAjODa3LJs',
    appId: '1:348513316290:ios:3e88b1def6e9a6a88aba5b',
    messagingSenderId: '348513316290',
    projectId: 'ufg-pfc-sonda-ph',
    storageBucket: 'ufg-pfc-sonda-ph.appspot.com',
    iosClientId: '348513316290-82vbdkigt50ge4m6dunomt1gg6m3il93.apps.googleusercontent.com',
    iosBundleId: 'br.ufg.pfc.phMobile',
  );
}
